# Generated by Django 5.2.8 on 2025-11-27 17:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=' Nome para Contato')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Contato')),
                ('mensagem', models.CharField(max_length=500, verbose_name='Mesagem para Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_site', models.CharField(max_length=100, verbose_name='Nome do Site')),
                ('logo_do_site', models.ImageField(upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'png', 'jpg', 'jpeg'])], verbose_name='Logo do Site')),
                ('texto_chamada', models.TextField(verbose_name='Texto da Chamada (Hero)')),
                ('texto_sobre', models.TextField(verbose_name='Texto Sobre Nós')),
                ('imagem_sobre', models.ImageField(upload_to='sobre/', verbose_name='Imagem da Seção Sobre')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Número do WhatsApp')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Página',
                'verbose_name_plural': 'Configurações da Página',
            },
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plano', models.CharField(max_length=100, verbose_name='Tipo do Plano')),
                ('descricao_plano', models.CharField(max_length=120, verbose_name='Descrição do Plano')),
                ('preco_plano', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Plano')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('estoque_produto', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Estoque do Produto')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Produto')),
                ('descricao_produto', models.CharField(max_length=120, verbose_name='Descrição do Produto')),
                ('imagem_produto', models.ImageField(upload_to='produtos/', verbose_name='Imagem dos Produtos ')),
                ('criado_em_produto', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em_produto', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='quantidade de Produto por Pedidos')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planos')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
    ]
