# Generated by Django 5.2.8 on 2025-11-26 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('estoque_produto', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Estoque do Produto')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Produto')),
                ('descricao_produto', models.CharField(max_length=120, verbose_name='Descrição do Produto')),
                ('imagem_produto', models.ImageField(upload_to='produtos/', verbose_name='Imagem dos Produtos ')),
                ('criado_em_produto', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em_produto', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
