# Generated by Django 5.2.8 on 2025-11-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=' Nome para Contato')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Contato')),
                ('mensagem', models.CharField(max_length=500, verbose_name='Mesagem para Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
