# Generated by Django 5.2.8 on 2025-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plano', models.CharField(max_length=100, verbose_name='Tipo do Plano')),
                ('descricao_plano', models.CharField(max_length=120, verbose_name='Descrição do Plano')),
                ('preco_plano', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Plano')),
            ],
        ),
    ]
